# DX 601 Week 8 Homework

## Introduction

In this homework, you will start practicing a variety of concepts from linear algebra.
We will dig in more deeply on all these concepts over the coming weeks.


## Example Code

You may find it helpful to refer to these GitHub repositories of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Problems

### Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [2]:
import math
import random

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import sklearn.linear_model

## Shared Data

### Abalone Data


In [4]:
abalone = pd.read_csv("abalone.tsv", sep="\t")

In [5]:
abalone

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera_weight  Shell_weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

### Problem 1

Given vector $\mathbf{v} = \begin{bmatrix} 3.6 \\ 3.4 \\ 9.4 \\ 5.4 \end{bmatrix}$, set `p1` to $v_2$.

Hint: don't forget that these indices start from zero.

In [6]:
# YOUR CHANGES HERE

p1 = 9.4

In [7]:
p1

9.4

### Problem 2

Given vector $\mathbf{u}$ stored in `q2` below, set `p2` to $u_{3}$.

In [8]:
# DO NOT CHANGE

q2 = np.array([1.6, 6.7, 1.9, 9.8, 9.3, 8.2, 7.4, 7. , 0.7, 5.4])
q2

array([1.6, 6.7, 1.9, 9.8, 9.3, 8.2, 7.4, 7. , 0.7, 5.4])

In [9]:
# YOUR CHANGES HERE

p2 = 9.8

In [10]:
p2

9.8

### Problem 3

Given matrix $\mathbf{A} = \begin{bmatrix} 3 & 6.4 & 2.3 \\ 1.3 & 5.2 & 7.2 \\ \end{bmatrix}$, set `p3` to $A_{1,1}$.

In [11]:
# YOUR CHANGES HERE

p3 = 5.2

In [12]:
p3

5.2

### Problem 4

Given the matrix $\mathbf{B}$ stored in `q4` below, set `p4` to $B_{2,3}$.

In [13]:
# DO NOT CHANGE

q4 = np.array([[3.4, 6.4, 8.6, 3.9],
               [2.7, 9.4, 5.8, 2.8],
               [3.9, 6.7, 9.9, 4.7],
               [7.1, 8.7, 5.9, 8.8]])
q4

array([[3.4, 6.4, 8.6, 3.9],
       [2.7, 9.4, 5.8, 2.8],
       [3.9, 6.7, 9.9, 4.7],
       [7.1, 8.7, 5.9, 8.8]])

In [14]:
# YOUR CHANGES HERE

p4 = 4.7

In [15]:
p4

4.7

### Problem 5

Set `p5` to the transpose of $\begin{bmatrix}2.6 & 4.2 \\ 3.3 & 6.2 \\ \end{bmatrix}$?

Hint:  Use `np.asarray` if you need help creating an array.

In [16]:
# YOUR CHANGES HERE

q5 = np.asarray([[2.6,4.2],[3.3,6.2]])
q5

array([[2.6, 4.2],
       [3.3, 6.2]])

In [17]:
p5 = q5.T

In [18]:
p5

array([[2.6, 3.3],
       [4.2, 6.2]])

### Problem 6

Set `p6` to $\begin{bmatrix} 1 & 2 \\ \end{bmatrix} \begin{bmatrix} 3 & 4 \\ 2.5 & 3.5 \\ \end{bmatrix}$.


Hint: You can do this by hand, or setup the correct arrays and use NumPy's @ operator for matrix multiplication.

In [19]:
q6a = np.asarray([[1,2]])
q6a

array([[1, 2]])

In [20]:
q6b = np.asarray([[3,4],[2.5,3.5]])
q6b

array([[3. , 4. ],
       [2.5, 3.5]])

In [21]:
q6a@q6b

array([[ 8., 11.]])

In [22]:
# YOUR CHANGES HERE

p6 = q6a@q6b

In [23]:
p6

array([[ 8., 11.]])

### Problem 7

Given $B = \begin{bmatrix} 0.2 & 0.8 \\ 0.3 & 0.7 \\ \end{bmatrix}$ which is stored in `q7`, set `p7` to $B B^T$?

Hint: this will be much more convenient to calculate using the `.T` attribute of NumPy arrays which returns the array's transpose, and the `@` operator for matrix multiplication.

In [24]:
# DO NOT CHANGE

q7 = np.array([[0.2, 0.8], [0.3, 0.7]])
q7

array([[0.2, 0.8],
       [0.3, 0.7]])

In [25]:
# DO NOT CHANGE

q7.T

array([[0.2, 0.3],
       [0.8, 0.7]])

In [26]:
# YOUR CHANGES HERE

p7 = q7@(q7.T)

In [27]:
p7

array([[0.68, 0.62],
       [0.62, 0.58]])

### Problem 8

What is the final shape from multiplying matrices of the following sequence of sizes? $3 \times 6, 6 \times 234, 234 \times 5, 5 \times 155, 155 \times 2$.
Set `p8` to your answer a tuple of two integers.

Hint: if the output of the matrix multiplication will have dimensions $m \times n$, the tuple should be `(m, n)`.

In [28]:
# YOUR CHANGE HERE

p8 = (3,2)

In [29]:
p8

(3, 2)

### Problem 9

Consider a fully connected neural network with 2 inputs, 1 hidden layer of width 1024, and 1 output.
How many elements are in each of the weight matrices?
Set `p9` to be a list of the number of elements in each weight matrix starting from the input side of the neural network.

In [68]:
# YOUR CHANGES HERE

p9 = [2048, 1024]

In [69]:
p9

[2048, 1024]

### Problem 10

Consider a fully connected neural network with 2 inputs, 3 hidden layers of width 1024, and 1 output.
How many elements are in each of the weight matrices?
Set `p10` to be a list of the number of elements in each weight matrix starting from the input side of the neural network.

In [70]:
# YOUR CHANGES HERE

p10 = [2048, 1048576, 1048576, 1024]

In [71]:
p10

[2048, 1048576, 1048576, 1024]

### Problem 11

Write a function `p11` taking in a vector as input and calculating its magnitude.

Hint: There are several ways to do this depending whether you are comfortable with NumPy or not.
A pure Python implementation will have many similar elements to calculating the standard deviation back in week 2.

In [34]:
# YOUR CHANGES HERE

def p11(v):
    magnitude = math.sqrt(sum(x**2 for x in v))
    return magnitude

In [35]:
# this should return 5
p11([3, 4])

5.0

### Problem 12

Write a function `p12` that takes in a $3 \times 3$ matrix $A$ and computes the sum of the entries on the diagonal.

This function is called the trace of $A$ and is defined for all sizes of square matrices, but you just need to handle $3 \times 3$ now.


Hint: Since you only need to handle a single size matrix, you can just write this as simple additions without loops.

In [64]:
# YOUR CHANGES HERE

def p12(A):
    diag =  np.diag(A)
    diag_sum = sum(diag)
    return diag_sum

In [62]:
t12a = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
t12a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [65]:
# this should return 3
p12(t12a)

np.int64(3)

In [66]:
t12b = np.array([[5,1,3], [2,5,5], [6, 1, 3]])
t12b

array([[5, 1, 3],
       [2, 5, 5],
       [6, 1, 3]])

In [67]:
# this should return 13
p12(t12b)

np.int64(13)

### Problem 13

Set `p13` to be a tuple of the $x$ and $y$ values solving the following two equations.

\begin{array}{rcl}
3x + 4y & = & 18 \\
-2x + 5y & = & 11 \\
\end{array}

Hint: This is an easy instance where both $x$ and $y$ are small integers.
You can solve it by plotting both lines as done in one of the videos and checking where they intersect.
Of course, you should check your answer by plugging it back into the previous equations.

In [83]:
x = np.linspace(-10, 10, 100)

# 2. Define your formula
y1 = (3/4)*x + (4.5)
y2 = (2/5)*x + (11/5)

plt.plot(x, y1, color='green')
plt.plot(x, y2, color='red')

# 4. Add labels and title
plt.xlabel('x')
plt.ylabel('y')
plt.title('Linear Function Plot')
plt.legend()

# 5. Show the plot
plt.grid(True)
plt.show()

/tmp/ipykernel_3509/2179106802.py:14: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


In [84]:
# YOUR CHANGES HERE

# set p13 to be (x, y)
p13 = (-6.57, -0.43)

In [85]:
p13

(-6.57, -0.43)

### Problem 14

Set `p14` to be the vector from the following list with the highest magnitude.

* $[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]$
* $[2, 2, 2, 2, 2]$
* $[3, 3, 3]$
* $[4, 4]$
* $[5]$

In [87]:
p14_list = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3],
    [4, 4],
    [5]
]

In [88]:
for x in p14_list:
    output = p11(x)
    print (f"{x}: {output}")

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]: 3.1622776601683795
[2, 2, 2, 2, 2]: 4.47213595499958
[3, 3, 3]: 5.196152422706632
[4, 4]: 5.656854249492381
[5]: 5.0


In [89]:
# YOUR CHANGES HERE

p14 = [4,4]

In [90]:
p14

[4, 4]

### Problem 15

Which of the following vectors could **not** be a principal component from PCA?

a. $[\frac{1}{2}, 0, \frac{1}{2}, 0, \frac{1}{2}, \frac{1}{2}]$

b. $[\frac{1}{4}, \frac{1}{4}, \frac{1}{2}]$

c. $[\frac{1}{4}, \frac{3}{4}, \frac{1}{4}, \frac{1}{2}, \frac{1}{4}]$

Set `p15` to "a", "b", or "c" to indicate your answer.

Hint: What parts of the principal components definition are not related to the data?

In [45]:
# YOUR CHANGES HERE

p15 = ...

### Problem 16

Set `p16` to the first principal component of the abalone data set.
Give it in the form of a one row data frame like in the Palmer Penguins example.

Hint: Don't forget the example code from the videos is linked in the repositories linked above.

In [46]:
# YOUR CHANGES HERE

p16 = ...

### Problem 17

The data in `q17` below was calculated using a quadratic formula of the form $y = ax^2 + bx + c$.

Set `p17a` to be a matrix suitable as input to linear regression to solve the quadratic regression problem.
That is, `p17a` should have columns $x^2$, $x$ and optionally $1$ depending on how you prefer to run the linear regression.

Run the linear regression problem, and set `p17b` to be a tuple of the coefficients from the quadratic regression problem.
If your analysis picks coefficients $a$, $b$, and $c$ as used above, then the answer should be `(a, b, c)`.

In [47]:
# DO NOT CHANGE

q17 = pd.DataFrame(data={"x": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], "y": [5, 6, 13, 26, 45, 70, 101, 138, 181, 230]})
q17

x    y
0  0    5
1  1    6
2  2   13
3  3   26
4  4   45
5  5   70
6  6  101
7  7  138
8  8  181
9  9  230

In [48]:
# YOUR CHANGES HERE

p17a = ...

In [49]:
p17a

Ellipsis

In [50]:
# YOUR CHANGES HERE

p17b = ...

In [51]:
p17b

Ellipsis

### Problem 18

Set `p18` to the inverse of the matrix $A$ in `q18`.

Hint: Try a few examples to understand what multiplying by matrix $A$ does to the other matrix.

In [52]:
# DO NOT CHANGE

q18 = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
q18

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [53]:
# YOUR CHANGES HERE

p18 = ...

In [54]:
# this will multiply p18 by q18 after you assign a matrix to p18.
# the result should be an identity matrix.

p18 @ q18 if isinstance(p18, type(q18)) else None


### Problem 19

Set `p19` to be the result of the matrix multiplication $\mathbf{XY}$ where $\mathbf{X}$ and $\mathbf{Y}$ are respectively stored in `x19` and `y19`.

Hint: While this could be solved by hand, we strongly encourage you to use NumPy's matrix multiplication support.
You can invoke it with the function [`np.matmul`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) or the `@` operator which invokes the save functionality.
Matrix multiplication is used a lot in linear algebra and it is worth knowing the easy ways to compute it.

In [55]:
# DO NOT CHANGE

x19 = np.array([[0, 6, 1, 9, 3],
       [3, 5, 9, 8, 4],
       [1, 5, 1, 6, 0],
       [6, 0, 0, 9, 8],
       [0, 7, 3, 5, 5]])
x19

array([[0, 6, 1, 9, 3],
       [3, 5, 9, 8, 4],
       [1, 5, 1, 6, 0],
       [6, 0, 0, 9, 8],
       [0, 7, 3, 5, 5]])

In [56]:
y19 = np.array([[1, 1, 7, 0, 9],
       [3, 9, 1, 9, 5],
       [3, 0, 4, 3, 4],
       [9, 7, 1, 3, 9],
       [2, 0, 5, 2, 6]])
y19

array([[1, 1, 7, 0, 9],
       [3, 9, 1, 9, 5],
       [3, 0, 4, 3, 4],
       [9, 7, 1, 3, 9],
       [2, 0, 5, 2, 6]])

In [57]:
# YOUR CHANGES HERE

p19 = ...

In [58]:
p19

Ellipsis

### Problem 20

Given the following chart, derive an equation for the line plotted in the form $ax + by = c$.
Set `p20` to be the tuple `(a, b, c)` that you derived.

Hint: the line intercepts are as simple as they appear. The $x$ intercept is at $y = 3$, and the $y$ intercept is at $x=5$.

In [59]:
# DO NOT CHANGE

xs = np.array([-1.        , -0.85714286, -0.71428571, -0.57142857, -0.42857143,
       -0.28571429, -0.14285714,  0.        ,  0.14285714,  0.28571429,
        0.42857143,  0.57142857,  0.71428571,  0.85714286,  1.        ,
        1.14285714,  1.28571429,  1.42857143,  1.57142857,  1.71428571,
        1.85714286,  2.        ,  2.14285714,  2.28571429,  2.42857143,
        2.57142857,  2.71428571,  2.85714286,  3.        ,  3.14285714,
        3.28571429,  3.42857143,  3.57142857,  3.71428571,  3.85714286,
        4.        ,  4.14285714,  4.28571429,  4.42857143,  4.57142857,
        4.71428571,  4.85714286,  5.        ,  5.14285714,  5.28571429,
        5.42857143,  5.57142857,  5.71428571,  5.85714286,  6.        ])
ys = np.array([ 3.6       ,  3.51428571,  3.42857143,  3.34285714,  3.25714286,
        3.17142857,  3.08571429,  3.        ,  2.91428571,  2.82857143,
        2.74285714,  2.65714286,  2.57142857,  2.48571429,  2.4       ,
        2.31428571,  2.22857143,  2.14285714,  2.05714286,  1.97142857,
        1.88571429,  1.8       ,  1.71428571,  1.62857143,  1.54285714,
        1.45714286,  1.37142857,  1.28571429,  1.2       ,  1.11428571,
        1.02857143,  0.94285714,  0.85714286,  0.77142857,  0.68571429,
        0.6       ,  0.51428571,  0.42857143,  0.34285714,  0.25714286,
        0.17142857,  0.08571429,  0.        , -0.08571429, -0.17142857,
       -0.25714286, -0.34285714, -0.42857143, -0.51428571, -0.6       ])

plt.axvline(x=0, color="grey")
plt.axhline(y=0, color="grey")
plt.plot(xs, ys)


In [60]:
# YOUR CHANGES HERE

p20 = ...

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR CHANGES HERE